file(READ "${PROJECT_SOURCE_DIR}/build-manifest.json" FGL_MANIFEST)
string(JSON manifest_standard GET "${FGL_MANIFEST}" standard)
if(NOT CMAKE_CXX_STANDARD EQUAL manifest_standard)
  message(FATAL_ERROR "CMake/MQB C++ standard drift")
endif()
if(MSVC AND NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
  message(FATAL_ERROR "The shared Windows build contract requires x64")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/build-manifest.json" "${PROJECT_SOURCE_DIR}/mqb.json")

function(fgl_array output)
  string(JSON count LENGTH "${FGL_MANIFEST}" ${ARGN})
  set(values)
  if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
      string(JSON item GET "${FGL_MANIFEST}" ${ARGN} ${index})
      list(APPEND values "${item}")
    endforeach()
  endif()
  set(${output} "${values}" PARENT_SCOPE)
endfunction()

if(MSVC)
  set(CMAKE_CONFIGURATION_TYPES "Debug;Release" CACHE STRING "Supported configurations" FORCE)
  set(CMAKE_CXX_FLAGS "" CACHE STRING "Compile policy comes from manifest" FORCE)
  set(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "Compile policy comes from manifest" FORCE)
  set(CMAKE_CXX_FLAGS_RELEASE "" CACHE STRING "Compile policy comes from manifest" FORCE)
  set(CMAKE_EXE_LINKER_FLAGS_DEBUG "" CACHE STRING "Link policy comes from manifest" FORCE)
  set(CMAKE_EXE_LINKER_FLAGS_RELEASE "" CACHE STRING "Link policy comes from manifest" FORCE)
  set(CMAKE_CXX_STANDARD_LIBRARIES "" CACHE STRING "System libraries come from manifest" FORCE)
endif()

function(fgl_add_target target key)
  string(JSON type GET "${FGL_MANIFEST}" targets ${key} type)
  fgl_array(sources targets ${key} sources)
  fgl_array(groups targets ${key} groups)
  set(links)
  foreach(group IN LISTS groups)
    if(group STREQUAL "core" AND NOT key STREQUAL "core")
      list(APPEND links framegraph_core)
    else()
      fgl_array(group_sources groups ${group})
      list(APPEND sources ${group_sources})
    endif()
  endforeach()
  if(type STREQUAL "static")
    add_library(${target} STATIC ${sources})
  else()
    add_executable(${target} ${sources})
  endif()
  fgl_array(includes include_dirs)
  set(include_paths)
  foreach(directory IN LISTS includes)
    list(APPEND include_paths "${PROJECT_SOURCE_DIR}/${directory}")
  endforeach()
  target_include_directories(${target} PRIVATE ${include_paths})
  if(key STREQUAL "core")
    target_include_directories(${target} INTERFACE "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>" "$<INSTALL_INTERFACE:include>")
    target_compile_features(${target} PUBLIC cxx_std_23)
  endif()
  fgl_array(target_libraries targets ${key} libraries)
  if(WIN32)
    list(APPEND links ${target_libraries})
  endif()
  if(MSVC)
    fgl_array(common compiler_args)
    fgl_array(debug configurations debug compiler_args)
    fgl_array(release configurations release compiler_args)
    set(options ${common} "$<$<CONFIG:Debug>:${debug}>" "$<$<NOT:$<CONFIG:Debug>>:${release}>")
    fgl_array(debug_defs configurations debug defines)
    fgl_array(release_defs configurations release defines)
    set(definitions "$<$<CONFIG:Debug>:${debug_defs}>" "$<$<NOT:$<CONFIG:Debug>>:${release_defs}>")
    target_compile_definitions(${target} PRIVATE ${definitions})
    foreach(config debug release)
      string(JSON runtime GET "${FGL_MANIFEST}" configurations ${config} runtime)
      if(runtime STREQUAL "MTd")
        set(${config}_runtime MultiThreadedDebug)
      elseif(runtime STREQUAL "MT")
        set(${config}_runtime MultiThreaded)
      elseif(runtime STREQUAL "MDd")
        set(${config}_runtime MultiThreadedDebugDLL)
      elseif(runtime STREQUAL "MD")
        set(${config}_runtime MultiThreadedDLL)
      else()
        message(FATAL_ERROR "Unsupported runtime policy: ${runtime}")
      endif()
    endforeach()
    set(runtime "$<$<CONFIG:Debug>:${debug_runtime}>$<$<NOT:$<CONFIG:Debug>>:${release_runtime}>")
    set_property(TARGET ${target} PROPERTY MSVC_RUNTIME_LIBRARY "${runtime}")
    set_property(TARGET ${target} PROPERTY MSVC_DEBUG_INFORMATION_FORMAT "$<$<CONFIG:Debug>:Embedded>")
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION_DEBUG FALSE)
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE FALSE)
    if(type STREQUAL "exe")
      fgl_array(system_libraries msvc_system_libraries)
      list(APPEND links ${system_libraries})
      fgl_array(debug_link configurations debug linker_args)
      fgl_array(release_link configurations release linker_args)
      set(link_options "$<$<CONFIG:Debug>:${debug_link}>" "$<$<NOT:$<CONFIG:Debug>>:${release_link}>")
      target_link_options(${target} PRIVATE ${link_options})
    endif()
  else()
    set(options -Wall -Wextra -Wpedantic)
  endif()
  target_compile_options(${target} PRIVATE ${options})
  if(links)
    target_link_libraries(${target} PRIVATE ${links})
  endif()
  set_property(GLOBAL APPEND PROPERTY FGL_TARGETS ${target})
  foreach(pair SOURCES INCLUDE_DIRECTORIES COMPILE_OPTIONS COMPILE_DEFINITIONS LINK_LIBRARIES LINK_OPTIONS MSVC_RUNTIME_LIBRARY MSVC_DEBUG_INFORMATION_FORMAT INTERPROCEDURAL_OPTIMIZATION INTERPROCEDURAL_OPTIMIZATION_DEBUG INTERPROCEDURAL_OPTIMIZATION_RELEASE CXX_STANDARD CXX_EXTENSIONS CXX_STANDARD_REQUIRED COMPILE_FEATURES INTERFACE_COMPILE_FEATURES)
    get_target_property(value ${target} ${pair})
    if("${value}" MATCHES "-NOTFOUND$")
      set(value "")
    endif()
    set_property(TARGET ${target} PROPERTY FGL_EXPECTED_${pair} "${value}")
  endforeach()
endfunction()

function(fgl_verify_targets)
  if(MSVC)
    foreach(flag CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE CMAKE_EXE_LINKER_FLAGS_DEBUG CMAKE_EXE_LINKER_FLAGS_RELEASE CMAKE_CXX_STANDARD_LIBRARIES)
      if(NOT "${${flag}}" STREQUAL "")
        message(FATAL_ERROR "Out-of-manifest MSVC flag drift: ${flag}")
      endif()
    endforeach()
  endif()
  get_property(targets GLOBAL PROPERTY FGL_TARGETS)
  foreach(target IN LISTS targets)
    foreach(property SOURCES INCLUDE_DIRECTORIES COMPILE_OPTIONS COMPILE_DEFINITIONS LINK_LIBRARIES LINK_OPTIONS MSVC_RUNTIME_LIBRARY MSVC_DEBUG_INFORMATION_FORMAT INTERPROCEDURAL_OPTIMIZATION INTERPROCEDURAL_OPTIMIZATION_DEBUG INTERPROCEDURAL_OPTIMIZATION_RELEASE CXX_STANDARD CXX_EXTENSIONS CXX_STANDARD_REQUIRED COMPILE_FEATURES INTERFACE_COMPILE_FEATURES)
      get_target_property(actual ${target} ${property})
      if("${actual}" MATCHES "-NOTFOUND$")
        set(actual "")
      endif()
      get_target_property(expected ${target} FGL_EXPECTED_${property})
      if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "Build manifest drift: ${target} ${property}")
      endif()
    endforeach()
  endforeach()
  file(WRITE "${CMAKE_BINARY_DIR}/build-contract.json" "${FGL_MANIFEST}")
endfunction()
